
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sbo-perf-step-@@STEP@@
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sbo-perf-step-@@STEP@@
spec:
  source:
    git:
      ref: main
      uri: 'https://github.com/pmacik/sbo-on-sb-perf'
    type: Git
    contextDir: pipelines/sbo-perf/steps/@@STEP@@
    dockerfile: |
      FROM registry.redhat.io/ubi8/ubi
      ENV WORKSPACE /workspace
      ENV ARTIFACTS /mnt/artifacts
      ENV KUBECONFIG ${WORKSPACE}/kubeconfig
      ENV PATH $PATH:$WORKSPACE     
      RUN mkdir -p ${ARTIFACTS}
      RUN mkdir -p ${WORKSPACE}
      RUN yum install -y --nodocs wget git jq httpd-tools make golang python3-pip \
          && yum clean all
      RUN pip3 install yamllint yq
      ENV GIT_SSL_NO_VERIFY true
      RUN mkdir -p /context
      COPY * /context/
      ENTRYPOINT [ "/context/run.sh" ]
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: sbo-perf-step-@@STEP@@:latest
  triggers:
    - type: ConfigChange
