---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbo-perf-artifacts
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sbo-perf-artifacts
  template:
    metadata:
      labels:
        app: sbo-perf-artifacts
    spec:
      volumes:
        - name: sbo-perf-artifacts
          persistentVolumeClaim:
            claimName: sbo-perf-artifacts
            readOnly: true
      containers:
        - name: nginx
          image: image-registry.openshift-image-registry.svc:5000/sbo-perf/sbo-perf-artifacts:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: sbo-perf-artifacts
              mountPath: /usr/share/nginx/html
              readOnly: true
          imagePullPolicy: Always
      restartPolicy: Always
