---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sbo-perf-artifacts
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sbo-perf-artifacts
spec:
  source:
    dockerfile: |
      FROM nginx:alpine
      
      RUN echo -e "worker_processes auto;\n\
      error_log /var/log/nginx/error.log notice;\n\
      pid /var/run/nginx.pid;\n\
      events {\n\
        worker_connections 1024;\n\
      }\n\
      http {\n\
        include /etc/nginx/mime.types;\n\
        default_type application/octet-stream;\n\
        log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';\n\
        access_log /var/log/nginx/access.log  main;\n\
        sendfile on;\n\
        keepalive_timeout 65;\n\
        include /etc/nginx/conf.d/*.conf;\n\
        autoindex on;\n\
        autoindex_exact_size on;\n\
        autoindex_format html;\n\
        autoindex_localtime on;\n\
      }\n" > /etc/nginx/nginx.conf
      RUN sed -i -e 's,listen.*80;,listen 8080;,g' /etc/nginx/conf.d/default.conf
      RUN chgrp -R root /var/cache/nginx /var/run /var/log/nginx && chmod -R 770 /var/cache/nginx /var/run /var/log/nginx
      EXPOSE 8080
      ENTRYPOINT [ "/docker-entrypoint.sh", "nginx", "-g", "daemon off;"]
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: sbo-perf-artifacts:latest
  triggers:
    - type: ConfigChange
