---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sbo-perf
spec:
  params:
    - name: ocp-release
      type: string
      description: OCP Release
      default: "4.7"
    - name: ocp-version
      type: string
      description: OCP Version
      default: ""
    - name: ocp-release-dir
      type: string
      description: OCP release dir
      default: "ocp"
    - name: user-ns-prefix
      type: string
      description: Prefix of user namespaces
      default: "sbo-perf"
    - name: namespaces
      type: string
      description: Number of Namespaces to generate
      default: "10"
    - name: secrets
      type: string
      description: Number of number of secrets to generate per namespace
      default: "5"
    - name: configmaps
      type: string
      description: Number of config maps to generate per namespace
      default: "5"
    - name: values-per-secret
      type: string
      description: Number of values to generate per secret
      default: "5"
    - name: values-per-configmap
      type: string
      description: Number of values to generate per config map
      default: "5"
    - name: bindings
      type: string
      description: Number of application+backing service+2xservice binding sets to generate per namespace
      default: "1"
  tasks:
    - name: sbo-perf-setup
      taskRef:
        kind: Task
        name: sbo-perf-setup
      workspaces:
        - name: sandbox
          workspace: sandbox
        - name: metrics
          workspace: metrics
      timeout: 5h
      params:
        - name: ocp-release
          value: "$(params.ocp-release)"
        - name: ocp-version
          value: "$(params.ocp-version)"
        - name: ocp-release-dir
          value: "$(params.ocp-release-dir)"
    - name: sbo-perf-test
      taskRef:
        kind: Task
        name: sbo-perf-test
      runAfter:
        - sbo-perf-setup
      workspaces:
        - name: sandbox
          workspace: sandbox
        - name: metrics
          workspace: metrics
      timeout: 5h
      params:
        - name: user-ns-prefix
          value: "$(params.user-ns-prefix)"
        - name: namespaces
          value: "$(params.namespaces)"
        - name: secrets
          value: "$(params.secrets)"
        - name: configmaps
          value: "$(params.configmaps)"
        - name: values-per-secret
          value: "$(params.values-per-secret)"
        - name: values-per-configmap
          value: "$(params.values-per-configmap)"
        - name: bindings
          value: "$(params.bindings)"
    - name: sbo-perf-artifacts
      taskRef:
        kind: Task
        name: sbo-perf-artifacts
      runAfter:
        - sbo-perf-test
      workspaces:
        - name: sandbox
          workspace: sandbox
        - name: metrics
          workspace: metrics
        - name: artifacts
          workspace: artifacts
  workspaces:
    - name: sandbox
    - name: metrics
    - name: artifacts
